var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__faa2b439._.js")
R.c("server/chunks/ssr/botech_project_test-admin_moja-aplikacija_dd4300f4._.js")
R.c("server/chunks/ssr/965ac_next_dist_568047f8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d09fe8eb._.js")
R.c("server/chunks/ssr/965ac_e5df851c._.js")
R.c("server/chunks/ssr/965ac_next_dist_be1ac210._.js")
R.c("server/chunks/ssr/botech_project_test-admin_moja-aplikacija_src_app_6079832c._.js")
R.c("server/chunks/ssr/27752_moja-aplikacija__next-internal_server_app__global-error_page_actions_b2171fe5.js")
R.m(34785)
module.exports=R.m(34785).exports
