var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00be2cf5._.js")
R.c("server/chunks/ssr/botech_project_test-admin_moja-aplikacija_dd4300f4._.js")
R.c("server/chunks/ssr/965ac_next_dist_esm_build_templates_app-page_325bacd3.js")
R.c("server/chunks/ssr/[root-of-the-server]__d09fe8eb._.js")
R.c("server/chunks/ssr/965ac_e5df851c._.js")
R.c("server/chunks/ssr/965ac_next_dist_be1ac210._.js")
R.c("server/chunks/ssr/botech_project_test-admin_moja-aplikacija_src_app_6079832c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__957b41cf._.js")
R.c("server/chunks/ssr/965ac_next_dist_client_components_bc3c51aa._.js")
R.c("server/chunks/ssr/965ac_next_dist_client_components_builtin_forbidden_2c0e3926.js")
R.c("server/chunks/ssr/27752_moja-aplikacija__next-internal_server_app__not-found_page_actions_28c7c56f.js")
R.m(95192)
module.exports=R.m(95192).exports
