var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/add/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__bafd52b6._.js")
R.c("server/chunks/ssr/botech_project_test-admin_moja-aplikacija_dd4300f4._.js")
R.c("server/chunks/ssr/botech_project_test-admin_moja-aplikacija_3bb94205._.js")
R.c("server/chunks/ssr/[root-of-the-server]__82f07af0._.js")
R.c("server/chunks/ssr/965ac_e5df851c._.js")
R.c("server/chunks/ssr/965ac_next_dist_be1ac210._.js")
R.c("server/chunks/ssr/botech_project_test-admin_moja-aplikacija_src_app_6079832c._.js")
R.c("server/chunks/ssr/965ac_next_dist_client_components_builtin_global-error_66ac736f.js")
R.c("server/chunks/ssr/[root-of-the-server]__957b41cf._.js")
R.c("server/chunks/ssr/965ac_next_dist_client_components_bc3c51aa._.js")
R.c("server/chunks/ssr/965ac_next_dist_client_components_builtin_forbidden_2c0e3926.js")
R.c("server/chunks/ssr/965ac_next_dist_client_components_builtin_unauthorized_633fcd40.js")
R.c("server/chunks/ssr/56529_test-admin_moja-aplikacija__next-internal_server_app_add_page_actions_b327a370.js")
R.m(25221)
module.exports=R.m(25221).exports
