var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/items/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__8026e6d4._.js")
R.c("server/chunks/ssr/botech_project_test-admin_moja-aplikacija_dd4300f4._.js")
R.c("server/chunks/ssr/botech_project_test-admin_moja-aplikacija_b3c484f2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__82f07af0._.js")
R.c("server/chunks/ssr/965ac_e5df851c._.js")
R.c("server/chunks/ssr/965ac_next_dist_be1ac210._.js")
R.c("server/chunks/ssr/botech_project_test-admin_moja-aplikacija_src_app_6079832c._.js")
R.c("server/chunks/ssr/965ac_next_dist_client_components_builtin_global-error_66ac736f.js")
R.c("server/chunks/ssr/[root-of-the-server]__957b41cf._.js")
R.c("server/chunks/ssr/965ac_next_dist_client_components_bc3c51aa._.js")
R.c("server/chunks/ssr/965ac_next_dist_client_components_builtin_forbidden_2c0e3926.js")
R.c("server/chunks/ssr/965ac_next_dist_client_components_builtin_unauthorized_633fcd40.js")
R.c("server/chunks/ssr/27752_moja-aplikacija__next-internal_server_app_items_[slug]_page_actions_29b442af.js")
R.m(29728)
module.exports=R.m(29728).exports
